### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by manuasir** [manuasir/film-recommendator#11]
Find a way to get the actual data. Some APIs, or some open databases. Whatever, but do it.

**Comment by JavRip** [comment]
I've found a couple of free APIs that could work for us:
- OMDb API (https://www.omdbapi.com/apikey.aspx)
- TMDb API (https://www.themoviedb.org/?language=es-ES)

Both are for movies and are up-to-date with people maintaining it.

I've also found some other interesting APIs if we want to get into TV Shows aswell, but I think that could be a discussion for another issue.

**Comment by valglez** [comment]
Both options seem interesting, and they also have Python libraries:

- OMDb API (https://pypi.org/project/omdbapi/)
- TMDb API (https://pypi.org/project/tmdb-python/)
