### ISSUE TITLE
[Discuss] Technology

### ISSUE THREAD

**Issue by manuasir** [manuasir/film-recommendator#3]
We should choose a programming language to implement the application core. Use this issue as a forum thread.

**Comment by valglez** [comment]
Hi team,

I would like to use C# because I believe it's a good opportunity to learn this programming language and add it to my skills. I understand that you are more familiar with Python, so I also hope to hear your opinion.

Cheers.

**Comment by Santiagoestremadoyro** [comment]
Hi, it would be perfect for me to use C since I would like to learn more about this programming language.

**Comment by JavRip** [comment]
Hi team,

I agree with @valglez, I'd also like to improve my skills in C#, since I'm still learning. I would'nt be against programming with Python if the rest of you prefer that language.

**Comment by valglez** [comment]
Okay, let's do it with Python. Assigned this issue to me @manuasir, please.
